kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ include "testflask-build-source.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testflask-build-source.labels" . | nindent 4 }}
  {{- with .Values.buildConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: {{ include "testflask-build-source.name" . }}:latest
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: {{ .Values.buildStrategy }}
    {{- if eq .Values.buildStrategy "Source" }}
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'python:3.6-ubi8'
    {{- end }}
  postCommit: {}
  source:
    type: Git
    git:
      uri: {{ .Values.gitURL }}
  runPolicy: Serial
status:
  lastVersion: 0
