{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: {{ include "testflask-build-source.clusterRoleBinding" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: {{ include "testflask-build-source.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
