apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ include "testFlask-Build-Source.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "testFlask-Build-Source.labels" . | nindent 4 }}
  {{- with .Values.buildConfig.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "testFlask-Build-Source.name" . }}
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: {{ printf "%s/%s/%s" .Values.buildConfig.is_url .Release.Namespace ( include testFlask-Build-Source.name )}}
